// ** Custom Components
import CustomChip from 'src/@core/components/mui/chip'
import { chipStatus } from 'src/components/states/chips'

// ** Icon import
import { Icon } from '@iconify/react'

export const columns = () => {
  return [
    {
      name: 'Asset Name',
      sortable: true,
      selector: row => row.name
    },
    {
      name: 'Date/Time',
      sortable: true,
      selector: row => `${row.date.split('T')[0]}\n${row.date.split('T')[1]}`
    },
    {
      name: 'ACC',
      sortable: true,
      selector: row => row.acc
    },
    {
      name: 'MMCX',
      sortable: true,
      selector: row => row.mmcx
    },
    {
      name: 'Latitude',
      sortable: true,
      selector: row => row.latitude
    },
    {
      name: 'Longitude',
      sortable: true,
      selector: row => row.longitude
    },
    {
      name: 'Speed',
      sortable: true,
      selector: row => row.speed
    },
    {
      name: 'Course',
      sortable: true,
      selector: row => row.course
    },
    {
      name: 'Height',
      sortable: true,
      selector: row => row.height
    },
    {
      name: 'Current Trip Fuel Consumption',
      sortable: true,
      selector: row => row.fuel_consumption
    },
    {
      name: 'Current Trip Mileage',
      sortable: true,
      selector: row => row.trip_mileage
    },

    {
      name: 'Voltage',
      sortable: true,
      cell: row => (
        <CustomChip
          size='small'
          skin='light'
          color={chipStatus[row.ignition_status]?.color}
          label={
            <Icon
              icon={chipStatus[row.ignition_status]?.icon}
              width='15'
              height='15'
              color={chipStatus[row.ignition_status]?.color}
            />
          }
          sx={{
            padding: '0.9rem 0rem'
          }}
        />
      )
    },
  ]
}

export const rows = [
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890',
    name: '2DFG54',
    address: 'N/A',
    driver: 'Available',
    vin: 'N/A',
    acc: 'N/A',
    mmcx: 'Not Found',
    course: 'obd',
    height: '12 feet',
    pid1: 'N/A',
    pid2: 'N/A',
    pid3: 'N/A',
    pid4: 'N/A',
    pid5: 'N/A',
    pid6: 'N/A',
    pid7: 'N/A',
    pid8: 'N/A',
    pid9: 'N/A',
    pid10: 'N/A',
    fuel_consumption: 'High',
    trip_mileage: 'Average',
    gsensor1_xaxis: 'N/A',
    gsensor1_yaxis: 'N/A',
    gsensor1_zaxis: 'N/A',
    gsensor2_xaxis: 'N/A',
    gsensor2_yaxis: 'N/A',
    gsensor2_zaxis: 'N/A',
    gsensor3_xaxis: 'N/A',
    gsensor3_yaxis: 'N/A',
    gsensor3_zaxis: 'N/A',
    gsensor4_xaxis: 'N/A',
    gsensor4_yaxis: 'N/A',
    gsensor4_zaxis: 'N/A',
    gsensor5_xaxis: 'N/A',
    gsensor5_yaxis: 'N/A',
    gsensor5_zaxis: 'N/A',
    no_dtc: '10',
    engine_coolant_temp: '50 Degree Centigrade',
    fuel_trim: 'N/A',
    fuel_pressure: 'N/A',
    intake_map: 'N/A',
    rpm: 'N/A',
    timing_advance: '1000ms',
    maf: 'N/A',
    throttle_pos: 'Not Found',
    runtime_engine_start: 'N/A',
    distance_traveled: '20 kms',
    relative_fuel_rail_pressure: 'N/A',
    commanded_egr: 'N/A',
    erg_error: '400',
    fuel_level: 'High',
    distance_codes_clear: 'true',
    barometic_pressure: 'Not Found',
    control_module_voltage: 'Not Found',
    load_value: 'Not Found',
    air_temperature: 'Normal',
    time_run_mil_on: 'N/A',
    time_sincecodes: 'N/A',
    absolute_fuel_rail_pressure: 'N/A',
    hybrid_battery_life: 'Average',
    engine_oil_temperature: 'Good',
    fuel_injection_time: '50s',
    fault_codes: 'Not Found',
    fuel_rate: 'N/A',
    engine_load: 'Normal'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890',
    name: '2DFG54',
    address: 'N/A',
    driver: 'Available',
    vin: 'N/A',
    acc: 'N/A',
    mmcx: 'Not Found',
    course: 'obd',
    height: '12 feet',
    pid1: 'N/A',
    pid2: 'N/A',
    pid3: 'N/A',
    pid4: 'N/A',
    pid5: 'N/A',
    pid6: 'N/A',
    pid7: 'N/A',
    pid8: 'N/A',
    pid9: 'N/A',
    pid10: 'N/A',
    fuel_consumption: 'High',
    trip_mileage: 'Average',
    gsensor1_xaxis: 'N/A',
    gsensor1_yaxis: 'N/A',
    gsensor1_zaxis: 'N/A',
    gsensor2_xaxis: 'N/A',
    gsensor2_yaxis: 'N/A',
    gsensor2_zaxis: 'N/A',
    gsensor3_xaxis: 'N/A',
    gsensor3_yaxis: 'N/A',
    gsensor3_zaxis: 'N/A',
    gsensor4_xaxis: 'N/A',
    gsensor4_yaxis: 'N/A',
    gsensor4_zaxis: 'N/A',
    gsensor5_xaxis: 'N/A',
    gsensor5_yaxis: 'N/A',
    gsensor5_zaxis: 'N/A',
    no_dtc: '10',
    engine_coolant_temp: '50 Degree Centigrade',
    fuel_trim: 'N/A',
    fuel_pressure: 'N/A',
    intake_map: 'N/A',
    rpm: 'N/A',
    timing_advance: '1000ms',
    maf: 'N/A',
    throttle_pos: 'Not Found',
    runtime_engine_start: 'N/A',
    distance_traveled: '20 kms',
    relative_fuel_rail_pressure: 'N/A',
    commanded_egr: 'N/A',
    erg_error: '400',
    fuel_level: 'High',
    distance_codes_clear: 'true',
    barometic_pressure: 'Not Found',
    control_module_voltage: 'Not Found',
    load_value: 'Not Found',
    air_temperature: 'Normal',
    time_run_mil_on: 'N/A',
    time_sincecodes: 'N/A',
    absolute_fuel_rail_pressure: 'N/A',
    hybrid_battery_life: 'Average',
    engine_oil_temperature: 'Good',
    fuel_injection_time: '50s',
    fault_codes: 'Not Found',
    fuel_rate: 'N/A',
    engine_load: 'Normal'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890',
    name: '2DFG54',
    address: 'N/A',
    driver: 'Available',
    vin: 'N/A',
    acc: 'N/A',
    mmcx: 'Not Found',
    course: 'obd',
    height: '12 feet',
    pid1: 'N/A',
    pid2: 'N/A',
    pid3: 'N/A',
    pid4: 'N/A',
    pid5: 'N/A',
    pid6: 'N/A',
    pid7: 'N/A',
    pid8: 'N/A',
    pid9: 'N/A',
    pid10: 'N/A',
    fuel_consumption: 'High',
    trip_mileage: 'Average',
    gsensor1_xaxis: 'N/A',
    gsensor1_yaxis: 'N/A',
    gsensor1_zaxis: 'N/A',
    gsensor2_xaxis: 'N/A',
    gsensor2_yaxis: 'N/A',
    gsensor2_zaxis: 'N/A',
    gsensor3_xaxis: 'N/A',
    gsensor3_yaxis: 'N/A',
    gsensor3_zaxis: 'N/A',
    gsensor4_xaxis: 'N/A',
    gsensor4_yaxis: 'N/A',
    gsensor4_zaxis: 'N/A',
    gsensor5_xaxis: 'N/A',
    gsensor5_yaxis: 'N/A',
    gsensor5_zaxis: 'N/A',
    no_dtc: '10',
    engine_coolant_temp: '50 Degree Centigrade',
    fuel_trim: 'N/A',
    fuel_pressure: 'N/A',
    intake_map: 'N/A',
    rpm: 'N/A',
    timing_advance: '1000ms',
    maf: 'N/A',
    throttle_pos: 'Not Found',
    runtime_engine_start: 'N/A',
    distance_traveled: '20 kms',
    relative_fuel_rail_pressure: 'N/A',
    commanded_egr: 'N/A',
    erg_error: '400',
    fuel_level: 'High',
    distance_codes_clear: 'true',
    barometic_pressure: 'Not Found',
    control_module_voltage: 'Not Found',
    load_value: 'Not Found',
    air_temperature: 'Normal',
    time_run_mil_on: 'N/A',
    time_sincecodes: 'N/A',
    absolute_fuel_rail_pressure: 'N/A',
    hybrid_battery_life: 'Average',
    engine_oil_temperature: 'Good',
    fuel_injection_time: '50s',
    fault_codes: 'Not Found',
    fuel_rate: 'N/A',
    engine_load: 'Normal'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890',
    name: '2DFG54',
    address: 'N/A',
    driver: 'Available',
    vin: 'N/A',
    acc: 'N/A',
    mmcx: 'Not Found',
    course: 'obd',
    height: '12 feet',
    pid1: 'N/A',
    pid2: 'N/A',
    pid3: 'N/A',
    pid4: 'N/A',
    pid5: 'N/A',
    pid6: 'N/A',
    pid7: 'N/A',
    pid8: 'N/A',
    pid9: 'N/A',
    pid10: 'N/A',
    fuel_consumption: 'High',
    trip_mileage: 'Average',
    gsensor1_xaxis: 'N/A',
    gsensor1_yaxis: 'N/A',
    gsensor1_zaxis: 'N/A',
    gsensor2_xaxis: 'N/A',
    gsensor2_yaxis: 'N/A',
    gsensor2_zaxis: 'N/A',
    gsensor3_xaxis: 'N/A',
    gsensor3_yaxis: 'N/A',
    gsensor3_zaxis: 'N/A',
    gsensor4_xaxis: 'N/A',
    gsensor4_yaxis: 'N/A',
    gsensor4_zaxis: 'N/A',
    gsensor5_xaxis: 'N/A',
    gsensor5_yaxis: 'N/A',
    gsensor5_zaxis: 'N/A',
    no_dtc: '10',
    engine_coolant_temp: '50 Degree Centigrade',
    fuel_trim: 'N/A',
    fuel_pressure: 'N/A',
    intake_map: 'N/A',
    rpm: 'N/A',
    timing_advance: '1000ms',
    maf: 'N/A',
    throttle_pos: 'Not Found',
    runtime_engine_start: 'N/A',
    distance_traveled: '20 kms',
    relative_fuel_rail_pressure: 'N/A',
    commanded_egr: 'N/A',
    erg_error: '400',
    fuel_level: 'High',
    distance_codes_clear: 'true',
    barometic_pressure: 'Not Found',
    control_module_voltage: 'Not Found',
    load_value: 'Not Found',
    air_temperature: 'Normal',
    time_run_mil_on: 'N/A',
    time_sincecodes: 'N/A',
    absolute_fuel_rail_pressure: 'N/A',
    hybrid_battery_life: 'Average',
    engine_oil_temperature: 'Good',
    fuel_injection_time: '50s',
    fault_codes: 'Not Found',
    fuel_rate: 'N/A',
    engine_load: 'Normal'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890',
    name: '2DFG54',
    address: 'N/A',
    driver: 'Available',
    vin: 'N/A',
    acc: 'N/A',
    mmcx: 'Not Found',
    course: 'obd',
    height: '12 feet',
    pid1: 'N/A',
    pid2: 'N/A',
    pid3: 'N/A',
    pid4: 'N/A',
    pid5: 'N/A',
    pid6: 'N/A',
    pid7: 'N/A',
    pid8: 'N/A',
    pid9: 'N/A',
    pid10: 'N/A',
    fuel_consumption: 'High',
    trip_mileage: 'Average',
    gsensor1_xaxis: 'N/A',
    gsensor1_yaxis: 'N/A',
    gsensor1_zaxis: 'N/A',
    gsensor2_xaxis: 'N/A',
    gsensor2_yaxis: 'N/A',
    gsensor2_zaxis: 'N/A',
    gsensor3_xaxis: 'N/A',
    gsensor3_yaxis: 'N/A',
    gsensor3_zaxis: 'N/A',
    gsensor4_xaxis: 'N/A',
    gsensor4_yaxis: 'N/A',
    gsensor4_zaxis: 'N/A',
    gsensor5_xaxis: 'N/A',
    gsensor5_yaxis: 'N/A',
    gsensor5_zaxis: 'N/A',
    no_dtc: '10',
    engine_coolant_temp: '50 Degree Centigrade',
    fuel_trim: 'N/A',
    fuel_pressure: 'N/A',
    intake_map: 'N/A',
    rpm: 'N/A',
    timing_advance: '1000ms',
    maf: 'N/A',
    throttle_pos: 'Not Found',
    runtime_engine_start: 'N/A',
    distance_traveled: '20 kms',
    relative_fuel_rail_pressure: 'N/A',
    commanded_egr: 'N/A',
    erg_error: '400',
    fuel_level: 'High',
    distance_codes_clear: 'true',
    barometic_pressure: 'Not Found',
    control_module_voltage: 'Not Found',
    load_value: 'Not Found',
    air_temperature: 'Normal',
    time_run_mil_on: 'N/A',
    time_sincecodes: 'N/A',
    absolute_fuel_rail_pressure: 'N/A',
    hybrid_battery_life: 'Average',
    engine_oil_temperature: 'Good',
    fuel_injection_time: '50s',
    fault_codes: 'Not Found',
    fuel_rate: 'N/A',
    engine_load: 'Normal'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890',
    name: '2DFG54',
    address: 'N/A',
    driver: 'Available',
    vin: 'N/A',
    acc: 'N/A',
    mmcx: 'Not Found',
    course: 'obd',
    height: '12 feet',
    pid1: 'N/A',
    pid2: 'N/A',
    pid3: 'N/A',
    pid4: 'N/A',
    pid5: 'N/A',
    pid6: 'N/A',
    pid7: 'N/A',
    pid8: 'N/A',
    pid9: 'N/A',
    pid10: 'N/A',
    fuel_consumption: 'High',
    trip_mileage: 'Average',
    gsensor1_xaxis: 'N/A',
    gsensor1_yaxis: 'N/A',
    gsensor1_zaxis: 'N/A',
    gsensor2_xaxis: 'N/A',
    gsensor2_yaxis: 'N/A',
    gsensor2_zaxis: 'N/A',
    gsensor3_xaxis: 'N/A',
    gsensor3_yaxis: 'N/A',
    gsensor3_zaxis: 'N/A',
    gsensor4_xaxis: 'N/A',
    gsensor4_yaxis: 'N/A',
    gsensor4_zaxis: 'N/A',
    gsensor5_xaxis: 'N/A',
    gsensor5_yaxis: 'N/A',
    gsensor5_zaxis: 'N/A',
    no_dtc: '10',
    engine_coolant_temp: '50 Degree Centigrade',
    fuel_trim: 'N/A',
    fuel_pressure: 'N/A',
    intake_map: 'N/A',
    rpm: 'N/A',
    timing_advance: '1000ms',
    maf: 'N/A',
    throttle_pos: 'Not Found',
    runtime_engine_start: 'N/A',
    distance_traveled: '20 kms',
    relative_fuel_rail_pressure: 'N/A',
    commanded_egr: 'N/A',
    erg_error: '400',
    fuel_level: 'High',
    distance_codes_clear: 'true',
    barometic_pressure: 'Not Found',
    control_module_voltage: 'Not Found',
    load_value: 'Not Found',
    air_temperature: 'Normal',
    time_run_mil_on: 'N/A',
    time_sincecodes: 'N/A',
    absolute_fuel_rail_pressure: 'N/A',
    hybrid_battery_life: 'Average',
    engine_oil_temperature: 'Good',
    fuel_injection_time: '50s',
    fault_codes: 'Not Found',
    fuel_rate: 'N/A',
    engine_load: 'Normal'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890',
    name: '2DFG54',
    address: 'N/A',
    driver: 'Available',
    vin: 'N/A',
    acc: 'N/A',
    mmcx: 'Not Found',
    course: 'obd',
    height: '12 feet',
    pid1: 'N/A',
    pid2: 'N/A',
    pid3: 'N/A',
    pid4: 'N/A',
    pid5: 'N/A',
    pid6: 'N/A',
    pid7: 'N/A',
    pid8: 'N/A',
    pid9: 'N/A',
    pid10: 'N/A',
    fuel_consumption: 'High',
    trip_mileage: 'Average',
    gsensor1_xaxis: 'N/A',
    gsensor1_yaxis: 'N/A',
    gsensor1_zaxis: 'N/A',
    gsensor2_xaxis: 'N/A',
    gsensor2_yaxis: 'N/A',
    gsensor2_zaxis: 'N/A',
    gsensor3_xaxis: 'N/A',
    gsensor3_yaxis: 'N/A',
    gsensor3_zaxis: 'N/A',
    gsensor4_xaxis: 'N/A',
    gsensor4_yaxis: 'N/A',
    gsensor4_zaxis: 'N/A',
    gsensor5_xaxis: 'N/A',
    gsensor5_yaxis: 'N/A',
    gsensor5_zaxis: 'N/A',
    no_dtc: '10',
    engine_coolant_temp: '50 Degree Centigrade',
    fuel_trim: 'N/A',
    fuel_pressure: 'N/A',
    intake_map: 'N/A',
    rpm: 'N/A',
    timing_advance: '1000ms',
    maf: 'N/A',
    throttle_pos: 'Not Found',
    runtime_engine_start: 'N/A',
    distance_traveled: '20 kms',
    relative_fuel_rail_pressure: 'N/A',
    commanded_egr: 'N/A',
    erg_error: '400',
    fuel_level: 'High',
    distance_codes_clear: 'true',
    barometic_pressure: 'Not Found',
    control_module_voltage: 'Not Found',
    load_value: 'Not Found',
    air_temperature: 'Normal',
    time_run_mil_on: 'N/A',
    time_sincecodes: 'N/A',
    absolute_fuel_rail_pressure: 'N/A',
    hybrid_battery_life: 'Average',
    engine_oil_temperature: 'Good',
    fuel_injection_time: '50s',
    fault_codes: 'Not Found',
    fuel_rate: 'N/A',
    engine_load: 'Normal'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890',
    name: '2DFG54',
    address: 'N/A',
    driver: 'Available',
    vin: 'N/A',
    acc: 'N/A',
    mmcx: 'Not Found',
    course: 'obd',
    height: '12 feet',
    pid1: 'N/A',
    pid2: 'N/A',
    pid3: 'N/A',
    pid4: 'N/A',
    pid5: 'N/A',
    pid6: 'N/A',
    pid7: 'N/A',
    pid8: 'N/A',
    pid9: 'N/A',
    pid10: 'N/A',
    fuel_consumption: 'High',
    trip_mileage: 'Average',
    gsensor1_xaxis: 'N/A',
    gsensor1_yaxis: 'N/A',
    gsensor1_zaxis: 'N/A',
    gsensor2_xaxis: 'N/A',
    gsensor2_yaxis: 'N/A',
    gsensor2_zaxis: 'N/A',
    gsensor3_xaxis: 'N/A',
    gsensor3_yaxis: 'N/A',
    gsensor3_zaxis: 'N/A',
    gsensor4_xaxis: 'N/A',
    gsensor4_yaxis: 'N/A',
    gsensor4_zaxis: 'N/A',
    gsensor5_xaxis: 'N/A',
    gsensor5_yaxis: 'N/A',
    gsensor5_zaxis: 'N/A',
    no_dtc: '10',
    engine_coolant_temp: '50 Degree Centigrade',
    fuel_trim: 'N/A',
    fuel_pressure: 'N/A',
    intake_map: 'N/A',
    rpm: 'N/A',
    timing_advance: '1000ms',
    maf: 'N/A',
    throttle_pos: 'Not Found',
    runtime_engine_start: 'N/A',
    distance_traveled: '20 kms',
    relative_fuel_rail_pressure: 'N/A',
    commanded_egr: 'N/A',
    erg_error: '400',
    fuel_level: 'High',
    distance_codes_clear: 'true',
    barometic_pressure: 'Not Found',
    control_module_voltage: 'Not Found',
    load_value: 'Not Found',
    air_temperature: 'Normal',
    time_run_mil_on: 'N/A',
    time_sincecodes: 'N/A',
    absolute_fuel_rail_pressure: 'N/A',
    hybrid_battery_life: 'Average',
    engine_oil_temperature: 'Good',
    fuel_injection_time: '50s',
    fault_codes: 'Not Found',
    fuel_rate: 'N/A',
    engine_load: 'Normal'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890',
    name: '2DFG54',
    address: 'N/A',
    driver: 'Available',
    vin: 'N/A',
    acc: 'N/A',
    mmcx: 'Not Found',
    course: 'obd',
    height: '12 feet',
    pid1: 'N/A',
    pid2: 'N/A',
    pid3: 'N/A',
    pid4: 'N/A',
    pid5: 'N/A',
    pid6: 'N/A',
    pid7: 'N/A',
    pid8: 'N/A',
    pid9: 'N/A',
    pid10: 'N/A',
    fuel_consumption: 'High',
    trip_mileage: 'Average',
    gsensor1_xaxis: 'N/A',
    gsensor1_yaxis: 'N/A',
    gsensor1_zaxis: 'N/A',
    gsensor2_xaxis: 'N/A',
    gsensor2_yaxis: 'N/A',
    gsensor2_zaxis: 'N/A',
    gsensor3_xaxis: 'N/A',
    gsensor3_yaxis: 'N/A',
    gsensor3_zaxis: 'N/A',
    gsensor4_xaxis: 'N/A',
    gsensor4_yaxis: 'N/A',
    gsensor4_zaxis: 'N/A',
    gsensor5_xaxis: 'N/A',
    gsensor5_yaxis: 'N/A',
    gsensor5_zaxis: 'N/A',
    no_dtc: '10',
    engine_coolant_temp: '50 Degree Centigrade',
    fuel_trim: 'N/A',
    fuel_pressure: 'N/A',
    intake_map: 'N/A',
    rpm: 'N/A',
    timing_advance: '1000ms',
    maf: 'N/A',
    throttle_pos: 'Not Found',
    runtime_engine_start: 'N/A',
    distance_traveled: '20 kms',
    relative_fuel_rail_pressure: 'N/A',
    commanded_egr: 'N/A',
    erg_error: '400',
    fuel_level: 'High',
    distance_codes_clear: 'true',
    barometic_pressure: 'Not Found',
    control_module_voltage: 'Not Found',
    load_value: 'Not Found',
    air_temperature: 'Normal',
    time_run_mil_on: 'N/A',
    time_sincecodes: 'N/A',
    absolute_fuel_rail_pressure: 'N/A',
    hybrid_battery_life: 'Average',
    engine_oil_temperature: 'Good',
    fuel_injection_time: '50s',
    fault_codes: 'Not Found',
    fuel_rate: 'N/A',
    engine_load: 'Normal'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890',
    name: '2DFG54',
    address: 'N/A',
    driver: 'Available',
    vin: 'N/A',
    acc: 'N/A',
    mmcx: 'Not Found',
    course: 'obd',
    height: '12 feet',
    pid1: 'N/A',
    pid2: 'N/A',
    pid3: 'N/A',
    pid4: 'N/A',
    pid5: 'N/A',
    pid6: 'N/A',
    pid7: 'N/A',
    pid8: 'N/A',
    pid9: 'N/A',
    pid10: 'N/A',
    fuel_consumption: 'High',
    trip_mileage: 'Average',
    gsensor1_xaxis: 'N/A',
    gsensor1_yaxis: 'N/A',
    gsensor1_zaxis: 'N/A',
    gsensor2_xaxis: 'N/A',
    gsensor2_yaxis: 'N/A',
    gsensor2_zaxis: 'N/A',
    gsensor3_xaxis: 'N/A',
    gsensor3_yaxis: 'N/A',
    gsensor3_zaxis: 'N/A',
    gsensor4_xaxis: 'N/A',
    gsensor4_yaxis: 'N/A',
    gsensor4_zaxis: 'N/A',
    gsensor5_xaxis: 'N/A',
    gsensor5_yaxis: 'N/A',
    gsensor5_zaxis: 'N/A',
    no_dtc: '10',
    engine_coolant_temp: '50 Degree Centigrade',
    fuel_trim: 'N/A',
    fuel_pressure: 'N/A',
    intake_map: 'N/A',
    rpm: 'N/A',
    timing_advance: '1000ms',
    maf: 'N/A',
    throttle_pos: 'Not Found',
    runtime_engine_start: 'N/A',
    distance_traveled: '20 kms',
    relative_fuel_rail_pressure: 'N/A',
    commanded_egr: 'N/A',
    erg_error: '400',
    fuel_level: 'High',
    distance_codes_clear: 'true',
    barometic_pressure: 'Not Found',
    control_module_voltage: 'Not Found',
    load_value: 'Not Found',
    air_temperature: 'Normal',
    time_run_mil_on: 'N/A',
    time_sincecodes: 'N/A',
    absolute_fuel_rail_pressure: 'N/A',
    hybrid_battery_life: 'Average',
    engine_oil_temperature: 'Good',
    fuel_injection_time: '50s',
    fault_codes: 'Not Found',
    fuel_rate: 'N/A',
    engine_load: 'Normal'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890',
    name: '2DFG54',
    address: 'N/A',
    driver: 'Available',
    vin: 'N/A',
    acc: 'N/A',
    mmcx: 'Not Found',
    course: 'obd',
    height: '12 feet',
    pid1: 'N/A',
    pid2: 'N/A',
    pid3: 'N/A',
    pid4: 'N/A',
    pid5: 'N/A',
    pid6: 'N/A',
    pid7: 'N/A',
    pid8: 'N/A',
    pid9: 'N/A',
    pid10: 'N/A',
    fuel_consumption: 'High',
    trip_mileage: 'Average',
    gsensor1_xaxis: 'N/A',
    gsensor1_yaxis: 'N/A',
    gsensor1_zaxis: 'N/A',
    gsensor2_xaxis: 'N/A',
    gsensor2_yaxis: 'N/A',
    gsensor2_zaxis: 'N/A',
    gsensor3_xaxis: 'N/A',
    gsensor3_yaxis: 'N/A',
    gsensor3_zaxis: 'N/A',
    gsensor4_xaxis: 'N/A',
    gsensor4_yaxis: 'N/A',
    gsensor4_zaxis: 'N/A',
    gsensor5_xaxis: 'N/A',
    gsensor5_yaxis: 'N/A',
    gsensor5_zaxis: 'N/A',
    no_dtc: '10',
    engine_coolant_temp: '50 Degree Centigrade',
    fuel_trim: 'N/A',
    fuel_pressure: 'N/A',
    intake_map: 'N/A',
    rpm: 'N/A',
    timing_advance: '1000ms',
    maf: 'N/A',
    throttle_pos: 'Not Found',
    runtime_engine_start: 'N/A',
    distance_traveled: '20 kms',
    relative_fuel_rail_pressure: 'N/A',
    commanded_egr: 'N/A',
    erg_error: '400',
    fuel_level: 'High',
    distance_codes_clear: 'true',
    barometic_pressure: 'Not Found',
    control_module_voltage: 'Not Found',
    load_value: 'Not Found',
    air_temperature: 'Normal',
    time_run_mil_on: 'N/A',
    time_sincecodes: 'N/A',
    absolute_fuel_rail_pressure: 'N/A',
    hybrid_battery_life: 'Average',
    engine_oil_temperature: 'Good',
    fuel_injection_time: '50s',
    fault_codes: 'Not Found',
    fuel_rate: 'N/A',
    engine_load: 'Normal'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890',
    name: '2DFG54',
    address: 'N/A',
    driver: 'Available',
    vin: 'N/A',
    acc: 'N/A',
    mmcx: 'Not Found',
    course: 'obd',
    height: '12 feet',
    pid1: 'N/A',
    pid2: 'N/A',
    pid3: 'N/A',
    pid4: 'N/A',
    pid5: 'N/A',
    pid6: 'N/A',
    pid7: 'N/A',
    pid8: 'N/A',
    pid9: 'N/A',
    pid10: 'N/A',
    fuel_consumption: 'High',
    trip_mileage: 'Average',
    gsensor1_xaxis: 'N/A',
    gsensor1_yaxis: 'N/A',
    gsensor1_zaxis: 'N/A',
    gsensor2_xaxis: 'N/A',
    gsensor2_yaxis: 'N/A',
    gsensor2_zaxis: 'N/A',
    gsensor3_xaxis: 'N/A',
    gsensor3_yaxis: 'N/A',
    gsensor3_zaxis: 'N/A',
    gsensor4_xaxis: 'N/A',
    gsensor4_yaxis: 'N/A',
    gsensor4_zaxis: 'N/A',
    gsensor5_xaxis: 'N/A',
    gsensor5_yaxis: 'N/A',
    gsensor5_zaxis: 'N/A',
    no_dtc: '10',
    engine_coolant_temp: '50 Degree Centigrade',
    fuel_trim: 'N/A',
    fuel_pressure: 'N/A',
    intake_map: 'N/A',
    rpm: 'N/A',
    timing_advance: '1000ms',
    maf: 'N/A',
    throttle_pos: 'Not Found',
    runtime_engine_start: 'N/A',
    distance_traveled: '20 kms',
    relative_fuel_rail_pressure: 'N/A',
    commanded_egr: 'N/A',
    erg_error: '400',
    fuel_level: 'High',
    distance_codes_clear: 'true',
    barometic_pressure: 'Not Found',
    control_module_voltage: 'Not Found',
    load_value: 'Not Found',
    air_temperature: 'Normal',
    time_run_mil_on: 'N/A',
    time_sincecodes: 'N/A',
    absolute_fuel_rail_pressure: 'N/A',
    hybrid_battery_life: 'Average',
    engine_oil_temperature: 'Good',
    fuel_injection_time: '50s',
    fault_codes: 'Not Found',
    fuel_rate: 'N/A',
    engine_load: 'Normal'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890',
    name: '2DFG54',
    address: 'N/A',
    driver: 'Available',
    vin: 'N/A',
    acc: 'N/A',
    mmcx: 'Not Found',
    course: 'obd',
    height: '12 feet',
    pid1: 'N/A',
    pid2: 'N/A',
    pid3: 'N/A',
    pid4: 'N/A',
    pid5: 'N/A',
    pid6: 'N/A',
    pid7: 'N/A',
    pid8: 'N/A',
    pid9: 'N/A',
    pid10: 'N/A',
    fuel_consumption: 'High',
    trip_mileage: 'Average',
    gsensor1_xaxis: 'N/A',
    gsensor1_yaxis: 'N/A',
    gsensor1_zaxis: 'N/A',
    gsensor2_xaxis: 'N/A',
    gsensor2_yaxis: 'N/A',
    gsensor2_zaxis: 'N/A',
    gsensor3_xaxis: 'N/A',
    gsensor3_yaxis: 'N/A',
    gsensor3_zaxis: 'N/A',
    gsensor4_xaxis: 'N/A',
    gsensor4_yaxis: 'N/A',
    gsensor4_zaxis: 'N/A',
    gsensor5_xaxis: 'N/A',
    gsensor5_yaxis: 'N/A',
    gsensor5_zaxis: 'N/A',
    no_dtc: '10',
    engine_coolant_temp: '50 Degree Centigrade',
    fuel_trim: 'N/A',
    fuel_pressure: 'N/A',
    intake_map: 'N/A',
    rpm: 'N/A',
    timing_advance: '1000ms',
    maf: 'N/A',
    throttle_pos: 'Not Found',
    runtime_engine_start: 'N/A',
    distance_traveled: '20 kms',
    relative_fuel_rail_pressure: 'N/A',
    commanded_egr: 'N/A',
    erg_error: '400',
    fuel_level: 'High',
    distance_codes_clear: 'true',
    barometic_pressure: 'Not Found',
    control_module_voltage: 'Not Found',
    load_value: 'Not Found',
    air_temperature: 'Normal',
    time_run_mil_on: 'N/A',
    time_sincecodes: 'N/A',
    absolute_fuel_rail_pressure: 'N/A',
    hybrid_battery_life: 'Average',
    engine_oil_temperature: 'Good',
    fuel_injection_time: '50s',
    fault_codes: 'Not Found',
    fuel_rate: 'N/A',
    engine_load: 'Normal'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890',
    name: '2DFG54',
    address: 'N/A',
    driver: 'Available',
    vin: 'N/A',
    acc: 'N/A',
    mmcx: 'Not Found',
    course: 'obd',
    height: '12 feet',
    pid1: 'N/A',
    pid2: 'N/A',
    pid3: 'N/A',
    pid4: 'N/A',
    pid5: 'N/A',
    pid6: 'N/A',
    pid7: 'N/A',
    pid8: 'N/A',
    pid9: 'N/A',
    pid10: 'N/A',
    fuel_consumption: 'High',
    trip_mileage: 'Average',
    gsensor1_xaxis: 'N/A',
    gsensor1_yaxis: 'N/A',
    gsensor1_zaxis: 'N/A',
    gsensor2_xaxis: 'N/A',
    gsensor2_yaxis: 'N/A',
    gsensor2_zaxis: 'N/A',
    gsensor3_xaxis: 'N/A',
    gsensor3_yaxis: 'N/A',
    gsensor3_zaxis: 'N/A',
    gsensor4_xaxis: 'N/A',
    gsensor4_yaxis: 'N/A',
    gsensor4_zaxis: 'N/A',
    gsensor5_xaxis: 'N/A',
    gsensor5_yaxis: 'N/A',
    gsensor5_zaxis: 'N/A',
    no_dtc: '10',
    engine_coolant_temp: '50 Degree Centigrade',
    fuel_trim: 'N/A',
    fuel_pressure: 'N/A',
    intake_map: 'N/A',
    rpm: 'N/A',
    timing_advance: '1000ms',
    maf: 'N/A',
    throttle_pos: 'Not Found',
    runtime_engine_start: 'N/A',
    distance_traveled: '20 kms',
    relative_fuel_rail_pressure: 'N/A',
    commanded_egr: 'N/A',
    erg_error: '400',
    fuel_level: 'High',
    distance_codes_clear: 'true',
    barometic_pressure: 'Not Found',
    control_module_voltage: 'Not Found',
    load_value: 'Not Found',
    air_temperature: 'Normal',
    time_run_mil_on: 'N/A',
    time_sincecodes: 'N/A',
    absolute_fuel_rail_pressure: 'N/A',
    hybrid_battery_life: 'Average',
    engine_oil_temperature: 'Good',
    fuel_injection_time: '50s',
    fault_codes: 'Not Found',
    fuel_rate: 'N/A',
    engine_load: 'Normal'
  }
]
