// ** Custom Components
import CustomChip from 'src/@core/components/mui/chip'
import { chipStatus } from 'src/components/states/chips'

// ** Icon import
import { Icon } from '@iconify/react'

export const columns = () => {
  return [
    {
      name: 'Asset Name',
      sortable: true,
      selector: row => row.name
    },
    {
      name: 'Date/Time',
      sortable: true,
      selector: row => `${row.date.split('T')[0]}\n${row.date.split('T')[1]}`
    },
    {
      name: 'VIn',
      sortable: true,
      selector: row => row.vin
    },
    {
      name: 'Connect',
      sortable: true,
      selector: row => row.connect
    },
    {
      name: 'Voltage',
      sortable: true,
      selector: row => `${row.speed} KM/H`
    },

    {
      name: 'Support Pid',
      sortable: true,
      selector: row => row.support_pid
    },
    {
      name: 'RPM',
      sortable: true,
      selector: row => `${row.speed} KM/H`
    },
    {
      name: 'Speed',
      sortable: true,
      selector: row => `${row.speed} KM/H`
    },
    {
      name: 'Coolant Temp',
      sortable: true,
      selector: row => row.coolant_temp
    },
    {
      name: 'Fuel Consumption',
      sortable: true,
      selector: row => row.fuel
    },
    {
      name: 'DTC Mileage',
      sortable: true,
      selector: row => row.dtc_mileage
    },
    {
      name: 'Mil Activated Distance',
      sortable: true,
      selector: row => row.mil_distance
    },
    {
      name: 'Mil  Status',
      sortable: true,
      selector: row => row.mil_status
    },
    {
      name: 'DTC  Number',
      sortable: true,
      selector: row => row.dtc_number
    },
    {
      name: 'Diagnostic Trouble Code',
      sortable: true,
      selector: row => row.diagnostic_code
    },
    {
      name: 'Throttle Position',
      sortable: true,
      selector: row => row.throttle_position
    },
    {
      name: 'Throttle Position',
      sortable: true,
      selector: row => row.engine_load
    },
    {
      name: 'Fuel Level Input',
      sortable: true,
      selector: row => row.fuel_level
    },
    {
      name: 'Protocol',
      sortable: true,
      selector: row => row.protocol
    },
    {
      name: 'Mileage',
      sortable: true,
      selector: row => row.mileage
    }
  ]
}

export const rows = [
  {
    name: '769IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '770IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '771IJA',
    status: 'stopped',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '773IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '774IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '1',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '770IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '771IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'stopped',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '773IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '774IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '1',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '770IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '771IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'stopped',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '773IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '774IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '1',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '770IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '771IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'stopped',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '773IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '774IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '1',
    latitude: '23.765788',
    longitude: '44.567890'
  },

  {
    name: '769IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '770IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '771IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'stopped',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '773IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '774IJA',
    connect: 'true',
    vin: 'none',
    support_pid: 'Yes',
    coolant_temp: ' Yes',
    fuel: '5.878 Litters',
    dtc_mileage: 'Not Found',
    mil_distance: '45 Km',
    mil_status: 'Activated',
    dtc_number: 'AWFF23',
    diagnostic_code: '404',
    throttle_position: 'Not Found',
    engine_load: 'Mild',
    fuel_level: 'High',
    protocol: 'Not Found',
    mileage: '23 Km',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '1',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '770IJA',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '771IJA',
    status: 'stopped',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '773IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '774IJA',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '1',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '770IJA',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '771IJA',
    status: 'stopped',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '773IJA',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '774IJA',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '1',
    latitude: '23.765788',
    longitude: '44.567890'
  }
]
