// ** Custom Components
import CustomChip from 'src/@core/components/mui/chip'
import { chipStatus } from 'src/components/states/chips'

// ** Icon import
import { Icon } from '@iconify/react'

export const columns = () => {
  return [
    {
      name: 'Driver',
      sortable: true,
      selector: row => row.driver
    },
    {
      name: 'Asset Name',
      sortable: true,
      selector: row => row.name
    },
    {
      name: 'Date/Time',
      sortable: true,
      selector: row => `${row.date.split('T')[0]}\n${row.date.split('T')[1]}`
    },
    {
      name: 'Working Hours (Travel Time)',
      sortable: true,
      selector: row => row.working_hours
    },
    {
      name: 'Allocation Working Hour',
      sortable: true,
      selector: row => row.allocation_hours
    },
    {
      name: 'Overtime Hours',
      sortable: true,
      selector: row => row.overtime_hours
    },
    {
      name: 'Overtime Charges',
      sortable: true,
      selector: row => row.overtime_charges
    }, 
  ]
}

export const rows = [
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    driver: 'Ibrahim',
    working_hours: '2 hours',
    allocation_hours: '5 hours',
    overtime_hours: '2 hours',
    overtime_charges: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  }
 
]
