// ** Custom Components
import CustomChip from 'src/@core/components/mui/chip'
import { chipStatus } from 'src/components/states/chips'

// ** Icon import
import { Icon } from '@iconify/react'

export const columns = () => {
  return [
    {
      name: 'Asset Name',
      sortable: true,
      selector: row => row.name
    },
    {
      name: 'Date/Time',
      sortable: true,
      selector: row => `${row.date.split('T')[0]}\n${row.date.split('T')[1]}`
    },
    {
      name: 'Inventory WASL Key',
      sortable: true,
      selector: row => row.inventory_wasl_key
    },
    {
      name: 'Warehouse WASL Key',
      sortable: true,
      selector: row => row.warehouse_wasl_key
    },
    {
      name: 'Warehouse',
      sortable: true,
      selector: row => row.warehouse
    },
    {
      name: 'Inventory',
      sortable: true,
      selector: row => row.inventory
    },
    {
      name: 'Sensor Id',
      sortable: true,
      selector: row => row.sensor_id
    },
    {
      name: 'Temp',
      sortable: true,
      selector: row => row.temp
    },
    {
      name: 'Humidity',
      sortable: true,
      selector: row => row.humidity
    },
    {
      name: 'Update Date',
      sortable: true,
      selector: row => `${row.date.split('T')[0]}\n${row.date.split('T')[1]}`
    },
    {
      name: 'Response',
      sortable: true,
      selector: row => row.response
    }
  ]
}

export const rows = [
  {
    name: '769IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '770IJA',
    status: 'driving',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '771IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'stopped',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '773IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '774IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '1',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '769IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '770IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'driving',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '44',
    odometer: '1234567',
    ignition_status: 'on',
    gps_status: 'on',
    gsm_status: 'on',
    battery: '100',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '771IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'stopped',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  },
  {
    name: '772IJA',
    inventory_wasl_key: '232109DD',
    warehouse_wasl_key: '4332asD',
    warehouse: 'Not Found',
    inventory: 'N/A',
    sensor_id: '62511',
    temp: 'Normal',
    humidity: 'Low',
    response: 'N/A',
    status: 'idle',
    date: '2021-05-01T12:00:00',
    address: 'King Fahad Road, Riyadh, Saudi Arabia',
    speed: '0',
    odometer: '1234567',
    ignition_status: 'off',
    gps_status: 'off',
    gsm_status: 'off',
    battery: '0',
    panic: '0',
    latitude: '23.765788',
    longitude: '44.567890'
  }
]
